#!/bin/bash
#
# upload.sh
# Creates a chroot-restricted SFTP/SCP upload-only user.
#
# Usage:
#   sudo ./upload.sh USERNAME PUBLIC_KEY_FILE
#
# Example:
#   sudo ./upload.sh customer01 ./customer01_ed25519.pub
#
# Upload:
#   scp file.zip customer01@server.example:/incoming/
#
# or:
#   sftp customer01@server.example
#   put file.zip /incoming/file.zip

set -Eeuo pipefail

readonly CHROOT_BASE="/srv/sftp"
readonly AUTHORIZED_KEYS_DIR="/etc/ssh/authorized_keys"
readonly SSHD_CONFIG_DIR="/etc/ssh/sshd_config.d"

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat >&2 <<EOF
Usage:
  sudo $0 USERNAME PUBLIC_KEY_FILE

Example:
  sudo $0 customer01 ./customer01_ed25519.pub
EOF
    exit 2
}

[[ $# -eq 2 ]] || usage
[[ $EUID -eq 0 ]] || die "This script must be run as root."

USERNAME="$1"
PUBLIC_KEY_FILE="$2"

# Intentionally restrict Linux usernames to a conservative character set.
[[ "$USERNAME" =~ ^[a-z_][a-z0-9_-]{0,30}$ ]] ||
    die "Invalid username: $USERNAME"

[[ -f "$PUBLIC_KEY_FILE" ]] ||
    die "Public key file not found: $PUBLIC_KEY_FILE"

command -v sshd >/dev/null ||
    die "OpenSSH Server is missing. Install it with: apt install openssh-server"

command -v useradd >/dev/null ||
    die "useradd was not found."

# Perform a basic validation of the supplied public key.
KEY_TYPE="$(awk 'NF { print $1; exit }' "$PUBLIC_KEY_FILE")"

case "$KEY_TYPE" in
    ssh-ed25519|ecdsa-sha2-*|sk-ssh-ed25519@openssh.com|sk-ecdsa-sha2-nistp256@openssh.com|ssh-rsa)
        ;;
    *)
        die "The file does not appear to contain a supported OpenSSH public key."
        ;;
esac

CHROOT_DIR="${CHROOT_BASE}/${USERNAME}"
UPLOAD_DIR="${CHROOT_DIR}/incoming"
KEY_DEST="${AUTHORIZED_KEYS_DIR}/${USERNAME}"
MATCH_CONFIG="${SSHD_CONFIG_DIR}/90-upload-${USERNAME}.conf"

if id "$USERNAME" >/dev/null 2>&1; then
    die "User '$USERNAME' already exists."
fi

if [[ -e "$CHROOT_DIR" ]]; then
    die "Chroot directory already exists: $CHROOT_DIR"
fi

if [[ -e "$MATCH_CONFIG" ]]; then
    die "SSH configuration already exists: $MATCH_CONFIG"
fi

# Verify that sshd_config includes the sshd_config.d directory.
if ! grep -Eq \
    '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/' \
    /etc/ssh/sshd_config; then
    die "/etc/ssh/sshd_config does not include sshd_config.d."
fi

printf 'Creating user %s ...\n' "$USERNAME"

# The user's home directory is "/" as seen from inside the chroot.
# Do not create a home directory and do not provide a regular login shell.
useradd \
    --home-dir / \
    --no-create-home \
    --shell /usr/sbin/nologin \
    --user-group \
    "$USERNAME"

# Lock password authentication.
# Public-key authentication remains available.
passwd --lock "$USERNAME" >/dev/null

# OpenSSH requires the chroot directory and all of its parent directories
# to be owned by root and not writable by the restricted user.
install -d -o root -g root -m 0755 "$CHROOT_BASE"
install -d -o root -g root -m 0755 "$CHROOT_DIR"

# Permissions 0733:
# - The user can enter the directory and create files.
# - The user cannot list the directory contents at filesystem level.
#
# SFTP operations are additionally restricted below.
install -d -o root -g "$USERNAME" -m 0733 "$UPLOAD_DIR"

# Store the public key outside the chroot.
install -d -o root -g root -m 0755 "$AUTHORIZED_KEYS_DIR"
install -o root -g root -m 0644 "$PUBLIC_KEY_FILE" "$KEY_DEST"

cat >"$MATCH_CONFIG" <<EOF
# Automatically generated by $0
Match User ${USERNAME}
    ChrootDirectory ${CHROOT_DIR}
    AuthorizedKeysFile ${KEY_DEST}

    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no

    # SFTP requests required for uploading files.
    #
    # Intentionally NOT permitted:
    #
    #   read       Read/download file contents
    #   readdir    List directory contents
    #   remove     Delete files
    #   rename     Rename files
    #   mkdir      Create directories
    #   rmdir      Remove directories
    #
    # lstat/stat are required by many SCP/SFTP clients.
    # They expose metadata but not file contents.
    ForceCommand internal-sftp -d /incoming -u 077 -p realpath,open,write,close,lstat,stat,fstat,setstat,fsetstat

    # Disable all SSH functionality that is not required for file uploads.
    DisableForwarding yes
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitTunnel no
    GatewayPorts no
EOF

chmod 0644 "$MATCH_CONFIG"
chown root:root "$MATCH_CONFIG"

# Validate the complete SSH server configuration before reloading sshd.
#
# If validation fails, remove everything created by this script so that
# the existing SSH service is not affected.
if ! sshd -t; then
    printf 'SSH configuration is invalid. Rolling back changes ...\n' >&2

    rm -f "$MATCH_CONFIG"
    rm -f "$KEY_DEST"
    rm -rf "$CHROOT_DIR"
    userdel "$USERNAME" 2>/dev/null || true

    die "sshd -t failed; all created objects have been removed."
fi

# Reload the SSH service without terminating existing SSH connections.
if systemctl is-active --quiet ssh; then
    systemctl reload ssh
elif systemctl is-active --quiet sshd; then
    systemctl reload sshd
else
    systemctl restart ssh 2>/dev/null ||
        systemctl restart sshd
fi

cat <<EOF

Upload-only user successfully created.

User:           ${USERNAME}
Chroot:         ${CHROOT_DIR}
Upload target:  /incoming
Public key:     ${KEY_DEST}
SSH config:     ${MATCH_CONFIG}

Upload using modern SCP:

  scp FILE ${USERNAME}@crj.circl.lu:/incoming/

Upload using SFTP:

  sftp ${USERNAME}@crj.circl.lu
  sftp> put FILE /incoming/FILE

Expected restrictions:

  ssh ${USERNAME}@crj.circl.lu
      No shell is available; only the internal SFTP subsystem is permitted.

  scp ${USERNAME}@crj.circl.lu:/incoming/FILE .
      Should fail because the SFTP "read" operation is not permitted.

  sftp> ls
      Should fail because the SFTP "readdir" operation is not permitted..

Important:

  Do not use legacy SCP mode ("scp -O").

  Legacy SCP requires execution of the server-side scp command.
  This is intentionally prevented by ForceCommand internal-sftp.
EOF
